<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Profile Menu</name>
   <tag></tag>
   <elementGuidId>3b76ef48-73a5-4ce9-b230-030b42f1bd79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.v-toolbar__content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/header/div/button[2]/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8883e95-1132-47dc-8339-57b35d2cff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-toolbar__content</value>
      <webElementGuid>d0f6ad7f-782d-4191-80e5-e220cbc5653d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AltaShop0</value>
      <webElementGuid>dbb7320e-67ad-4aeb-a4f0-a9058600b95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/header/div/button[2]/span/i</value>
      <webElementGuid>8ac946b3-ef44-456a-bbea-51195f17e2d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div</value>
      <webElementGuid>4c277602-272b-454a-b630-983db2892076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select category ...'])[1]/preceding::div[4]</value>
      <webElementGuid>2961ac16-2b36-42d5-8907-8165771c1d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>b5401380-4301-4679-a2f4-c0f1a585a157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AltaShop0' or . = 'AltaShop0')]</value>
      <webElementGuid>10f0f398-02cd-4ce8-acf5-44d292cc4091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
