<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-2367</name>
   <tag></tag>
   <elementGuidId>6f9ec3f2-16d8-4fb6-a6c3-fe0b4bece65a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2367</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-2367']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12d3e72a-fb80-44c2-846a-cccbd7d1e446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2367</value>
      <webElementGuid>0af1280e-16de-40b3-9bee-65d0100d1e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>453d3783-b488-4e36-9acf-248ddacc45a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2367&quot;)</value>
      <webElementGuid>7da4f95d-6083-4aff-8edb-5a42257a3a76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-2367']</value>
      <webElementGuid>b9d0e170-a6f7-4710-bf16-489ae237c62e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>49e130fe-01eb-48e0-848c-045af313b87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a00bcb97-8f05-4dfc-8a98-c2fc6ee8ffdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-2367' and @type = 'text']</value>
      <webElementGuid>c499b831-f15e-4f94-904c-1958f69afaf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
