<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-2370</name>
   <tag></tag>
   <elementGuidId>6a2d162e-4847-412f-9e64-4a6456e866d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2370</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-2370']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>531c5cdb-4caf-4657-b365-a834cc1b18c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-2370</value>
      <webElementGuid>16e09e6a-63f2-43ea-9fb8-c252d7bf1864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>031a0a35-0b90-489f-acaa-1eb7e53e4182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2370&quot;)</value>
      <webElementGuid>edbbc46e-8102-41c6-8c30-5d5deec22703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-2370']</value>
      <webElementGuid>72931d4f-f13d-40a4-8375-a85c3e4c58cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>21c9386f-4fdf-40ed-a8e0-9fdcb2393db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>1d1e98ab-f88c-4f1e-a565-2714c7d06681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-2370' and @type = 'text']</value>
      <webElementGuid>f771f74e-54d8-4b54-a553-ebcd4ffc751b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
