<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-1226</name>
   <tag></tag>
   <elementGuidId>3d39d1d1-dffe-44d1-a07d-175ec35e4a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1226</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1226']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f8e9739-c36b-4a72-8de7-3e873229a88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1226</value>
      <webElementGuid>3c6ee0c6-dee8-4745-8207-a3286d62f09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db48f8b3-e54b-4449-b858-6d6196be8193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1226&quot;)</value>
      <webElementGuid>9102e343-48ab-41ae-bda6-e1c2623f14cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1226']</value>
      <webElementGuid>cfc4c9e1-950a-493c-8864-b30ca5cbf7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>057cc5d2-fce5-4ab3-bb34-b81595533b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>63cff5b6-6a31-4099-9453-20a48ea72629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1226' and @type = 'text']</value>
      <webElementGuid>c689d234-03f3-4df5-9c88-abdaf85ce554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
