<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_input-1229</name>
   <tag></tag>
   <elementGuidId>f7fbdcc6-b255-421e-b72f-c1cd0e25eae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-1229</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-1229']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2ace2eb-c19f-4f20-9d05-2a0c1eb5237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1229</value>
      <webElementGuid>6605f70a-7640-44bb-a287-7c403d353ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0600a001-d2f7-40b9-8a91-f5fc4df8ac9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-1229&quot;)</value>
      <webElementGuid>1ff33de4-ea68-473f-9cc8-025a72ffee72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-1229']</value>
      <webElementGuid>5f56ad94-502b-4e7b-810e-07f3225d090b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>a93e190f-d6bf-4251-8602-fa928b104434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>aa6917cb-1c2e-4fe5-aef1-0e01f774effc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1229' and @type = 'text']</value>
      <webElementGuid>354234e7-fe56-43f7-ad79-f2c1898b7af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
